### ISSUE TITLE
github incomplete, unable to build

### ISSUE THREAD

**Issue by jadrian2006** [thetarkus/docker-funkwhale#12]
Cloning this repo: 

Step 5/11 : COPY ./src/api /app/api

There are no files in /src/api src just has the .git files.

**Comment by thetarkus** [comment]
Hi,
The `/src/api` directory is intentionally left empty as to not include Funkwhale's source in this repo (wouldn't work for different versions, etc.)

There's a few steps to manually building the image which are detailed in the [Build this image](https://github.com/thetarkus/docker-funkwhale#build-this-image) section of the README which include populating the directory using the `./scripts/download-artifact.sh` script

Let me know if you have any more issues
